action: train # train, validate or save
name: train_final_classifier
split: train
batch_size: 64
wandb_name: mldl23-ego-ta3n
wandb_dir: ./wandb

train:
  num_iter: 5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 5 # clips adopted in training
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 16

dataset:
  annotations_path: train_val
  shift: D1-D2
  workers: 4
  stride: 2
  resolution: 224
  RGB:
    data_path: ??
    features_name: saved_feat_I3D
  Event:
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: TA3NClassifier
    input_size: 1024
    hidden_size: 128
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-8
    temporal_aggregation: avgpool
    alpha: 0
    beta: [0.75, 0.75, 0.5]
    mu: 0
    reverse: False
